name: capstone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # UI & Image
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.0.17
  cached_network_image: ^3.3.1

  # AI Detection
  tflite_flutter:
    git:
      url: https://github.com/tensorflow/flutter-tflite.git
      ref: main

  # Core
  http: ^1.2.0
  shared_preferences: ^2.5.4
  google_sign_in: ^6.2.1
  
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  dio: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_temantukang.png
    - assets/images/panduankiri.jpeg
    - assets/images/google.png
    - assets/images/panduankanan.jpeg
    - assets/images/mengenali_kerusakan.jpg
    - assets/images/tips_renovasi.jpg
    - assets/models/labels.txt
    - assets/models/best.tflite